# Generated by Django 6.0 on 2026-04-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
