# Generated by Django 6.0 on 2026-04-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0055_bookmark_sensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English"), ("zh-hans", "Simplified Chinese")],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
