services:
  linkding:
    container_name: mylinkding
    image: "${LD_IMAGE_NAME:-linkding-local:latest}"
    build:
      context: .
      dockerfile: docker/default.Dockerfile
    ports:
      - "8991:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    network_mode: bridge
    restart: unless-stopped
